# Use an official node.js runtime as a parent image
FROM node:22-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and the package-lock.json files to the container
COPY package*.json .

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# ...existing code...

# Expose the port that the app runs on
EXPOSE 5003

# Run prisma generate and migrate before starting the server
CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && node ./src/server.js"]